sudo: required
dist: trusty
cache:
  apt: true
before_install:
- sudo apt-get -qq update && sudo apt-get install -y texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-publishers texlive-lang-portuguese
script:
- mkdir _build
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build manutencao.tex

before_deploy:
- git tag "v$(date +'%Y.%m.%d.%H%M')-$TRAVIS_BRANCH"

deploy:
  provider: releases
  api_key: $GIT_TOKEN
  file:
  - _build/manutencao.pdf
  skip_cleanup: true
  on:
    tags: true